version: "3"
services:
  spark-master:
    image: docker.io/bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./apps:/opt/apps
    ports:
      - "5200:8080"
      - "7077:7077"

  spark-worker:
    image: docker.io/bitnami/spark:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "5201:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  flight-aggregator:
    depends_on:
      - kafka
      - spark-master
    build:
      context: ./apps/flight-route-aggregator


networks:
  default:
    name: "spark-network"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

 # spark-worker:
 #    image: docker.io/bitnami/spark:latest
 #    container_name: spark-worker
 #    hostname: spark-worker
 #    user: root
 #    environment:
 #      - SPARK_MODE=worker
 #      - SPARK_MASTER_URL=spark://spark-master:7077
 #      # - SPARK_RPC_AUTHENTICATION_ENABLED=no
 #      # - SPARK_RPC_ENCRYPTION_ENABLED=no
 #      # - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
 #      # - SPARK_SSL_ENABLED=no
 #    ports:
 #      - "5201:8080"
 #      - "7000:7000"
 #    # volumes:
 #      # - ../streamingProje:/home
 #      # - /opt/spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
 #      # - /opt/spark/jars:/opt/bitnami/spark/ivy:z
